# Generated by Django 4.0.5 on 2022-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_picture',
            field=models.ImageField(null=True, upload_to='cover-picture/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
