# Generated by Django 4.0.5 on 2022-06-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_is_deleted_remove_postedit_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
